[pytest]
markers =
    functional: test for functional suite
    smoke: test for smoke suite
    elements: test for elements page suite
    login_success: test for login success suite
    login_failure: test for login failure suite
    sample_app_page: test for sample app page suite
    landing_page: test for landing page suite
    progress_bar_page: test for progress bar page suite
    alerts_page: test for alerts page suite
    alert_success: test for alert success suite
