[pytest]
markers =
    functional: test for functional suite
    smoke: test for smoke suite
    regression: test for regression suite
    elements: test for elements page suite
    sample_app_page: test for sample app page suite
        sample_app_page_success: test for sample app page success suite
        sample_app_page_failure: test for sample app page failure suite
    landing_page: test for landing page suite
    progress_bar_page: test for progress bar page suite
    alerts_page: test for alerts page suite
        alerts_page_success: test for alerts page success suite
        alerts_page_parametrize: test for alerts page parametrize suite
